package speakbox.ui;

import android.app.Fragment;
import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.SeekBar;
import android.widget.TextView;
import com.example.SpeakBox.R;
import com.firebase.client.Firebase;

import speakbox.model.Response;
import speakbox.util.Constants;

/**
 * Created by YingYing on 2016-04-03.
 * Displays the question, images and response method
 */
public class QuestionDisplayFragment extends Fragment{

    TextView userName;
    SeekBar seekBar;
    TextView seekBarValue;
    Button submitReponse;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        View rootView = inflater.inflate(R.layout.display_question, container, false);
        initializeScreen(rootView);

        userName.setText("Ying Ying"); // the user's name

        seekBar.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener() {
            @Override
            public void onProgressChanged(SeekBar seekBar, int i, boolean b) {
                seekBarValue.setText(String.valueOf(i));
            }

            @Override
            public void onStartTrackingTouch(SeekBar seekBar) {
                //auto-generated by IntelliJ
            }

            @Override
            public void onStopTrackingTouch(SeekBar seekBar) {
                //auto-generated by IntelliJ
            }
        });

        submitReponse.setOnClickListener(new Button.OnClickListener() {
            @Override
            public void onClick(View view) {
                submitResponse();
            }
        });

        return rootView;
    }

    private void initializeScreen(View rootView) {
        userName = (TextView) rootView.findViewById(R.id.userNameTextView);
        seekBar = (SeekBar) rootView.findViewById(R.id.rateSeekBar);
        seekBarValue = (TextView) rootView.findViewById(R.id.seekBarValueTextView);
        submitReponse = (Button) rootView.findViewById(R.id.submitButton);
    }

    private void submitResponse() {
        Firebase ref = new Firebase(Constants.FIREBASE_URL);
        String userEnteredName = userName.getText().toString();
        String response = seekBarValue.getText().toString();
        Response currentResponse = new Response("testId", response, userEnteredName);
        ref.child("activeResponse").setValue(currentResponse);
    }
}
